Repository pikvm/pikvm, pull requests merged in 2020-12, with the labels that each got.

#124 Added USB Splitter links for other countries
  README.md
Labels: resolution:fixed, type:feature

#135 Updated documentation
  img/chrome.png
  pages/building_os.md
  pages/troubleshooting.md
Labels: type:feature

#111 Clarify cables needed for v2
  README.md
Labels: component:documentation, type:feature
