Repository pikvm/pikvm, pull requests merged in 2020-11, with the labels that each got.

#103 Adding instructions for ezCoo managed KVM switch
  pages/ezCoo.md
Labels: component:documentation, resolution:fixed, type:feature

#106 how to disable mass storage in v2
  pages/cookbook.md
Labels: component:documentation, resolution:fixed

#108 Update building_os.md
  pages/building_os.md
Labels: component:documentation, resolution:fixed, type:feature

#114 Add instructions for 5GHz Wifi networks in the US
  pages/wifi_config.md
Labels: component:documentation, resolution:fixed, type:feature

#119 Update edid.md
  pages/edid.md
Labels: component:documentation, type:feature

#120 Update cookbook.md
  pages/cookbook.md
Labels: component:documentation, resolution:fixed, type:bug

#122 Add instructions on how to create a disk image on macOS
  pages/cookbook.md
Labels: component:documentation, resolution:fixed
