Repository pikvm/pikvm, pull requests merged in 2020-10, with the labels that each got.

#96 Update README.md
  README.md
Labels: component:documentation, resolution:fixed

#99 Update cookbook.md
  pages/cookbook.md
Labels: component:documentation, resolution:fixed, type:feature

#102 Fix some typos in README.md
  README.md
Labels: component:documentation, resolution:fixed, type:bug
