Repository pikvm/pikvm, pull requests merged in 2021-11, with the labels that each got.

#534 Update ezcoo.md
  docs/ezcoo.md
Labels: type:feature, resolution:fixed

#535 Update faq.md
  docs/faq.md
Labels: type:feature, resolution:fixed

#537 Update community_faq.md
  docs/community_faq.md
Labels: type:feature, resolution:fixed

#538 Update msd.md
  docs/msd.md
Labels: type:bug, resolution:fixed

#540 Update first_steps.md
  docs/first_steps.md
Labels: type:feature, resolution:fixed

#541 Update first_steps.md
  docs/first_steps.md
Labels: type:feature

#545 Update flashing_os.md
  docs/flashing_os.md
Labels: type:feature, resolution:fixed

#546 multiport.md: Fix Arduino typo
  docs/multiport.md
Labels: type:bug, resolution:fixed
