Repository pikvm/pikvm, pull requests merged in 2021-03, with the labels that each got.

#216 close li tag
  README.md
Labels: resolution:fixed, type:bug

#224 Update arduino_hid.md
  pages/arduino_hid.md
Labels: type:bug

#234 Update flashing_os.md
  pages/flashing_os.md
Labels: type:bug

#243 Update Community FAQ
  pages/Community FAQ
Labels: resolution:fixed, type:feature

#244 Update and rename Community FAQ to Community_FAQ.md
  pages/Community_FAQ.md
Labels: resolution:fixed

#247 Add formatting to community FAQ
  pages/Community_FAQ.md
Labels: resolution:fixed, type:feature

#248 Update ezcoo.md
  pages/ezcoo.md
Labels: resolution:fixed, type:bug
