Repository pikvm/pikvm, pull requests merged in 2021-08, with the labels that each got.

#421 Update flashing_os.md
  pages/flashing_os.md
Labels: type:feature

#420 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:feature, resolution:fixed

#425 Update multiport.md
  pages/multiport.md
Labels: type:bug, resolution:fixed

#428 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:bug, resolution:fixed

#427 Document servo module
  pages/gpio.md
Labels: type:feature, resolution:fixed

#432 Adding more pics
  img/CSI Wiring 2.jpg
  img/CSI Wiring w pcb spliter.jpg
  img/CSI Wiring.jpg
  img/CSI.jpg
  img/Direct Connect to Target.jpg
  img/Front of Target.jpg
  img/Front of rpi4 for usb capture.jpg
  img/Loop capture.jpg
  img/MALE TO MALE USB.jpg
  img/RPI4 USB PORT.jpg
  img/RPI4 USB.jpg
  img/Splitter+Blocker.jpg
  img/Target.jpg
  img/USB CAPTURE.jpg
  img/USB Capture Wiring.jpg
  img/USBC TO USBA W Spliter.jpg
Labels: type:feature
