Repository pikvm/pikvm, pull requests merged in 2021-02, with the labels that each got.

#166 SPI and multiport Updates
  img/arduino_spi_hid.png
  img/arduino_spi_hid_bb.jpg
  img/arduino_spi_hid_rpi.jpg
  pages/arduino_hid.md
  pages/multiport.md
Labels: resolution:fixed, type:feature

#176 Update video.md
  pages/video.md
Labels: resolution:fixed, type:bug

#175 Update vnc.md
  pages/vnc.md
Labels: resolution:fixed, type:bug

#174 Update wifi_config.md
  pages/wifi_config.md
Labels: resolution:fixed, type:bug

#173 Update multiport.md
  pages/multiport.md
Labels: resolution:fixed, type:bug

#177 Update tailscale.md
  pages/tailscale.md
Labels: resolution:fixed, type:bug

#178 Update config.md
  pages/config.md
Labels: resolution:fixed, type:bug

#196 Fix passphrases typo
  pages/vnc.md
Labels: resolution:fixed, type:bug

#200 Update usb_ethernet.md
  pages/usb_ethernet.md
Labels: type:feature

#213 Added Aimos 8port KVM HDMI switch
  pages/multiport.md
Labels: resolution:fixed, type:feature
