Repository pikvm/pikvm, pull requests merged in 2021-09, with the labels that each got.

#437 Update mouse.md
  pages/mouse.md
Labels: type:bug, resolution:fixed

#438 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: resolution:fixed, type:question

#439 Update msd.md
  pages/msd.md
Labels: type:feature, resolution:fixed

#443 Create Wiring Examples.md
  pages/Wiring Examples.md
Labels: type:feature, resolution:fixed

#441 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:feature, resolution:fixed

#442 Update msd.md
  pages/msd.md
Labels: type:feature, resolution:fixed

#444 Update Wiring Examples.md
  pages/Wiring Examples.md
Labels: type:bug, resolution:fixed

#445 Update README.md
  README.md
Labels: type:feature, resolution:fixed

#446 Update 3d_printing.md
  pages/3d_printing.md
Labels: type:feature, resolution:fixed

#464 Update wol.md
  pages/wol.md
Labels: type:feature, resolution:fixed

#466 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:bug

#467 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:feature, resolution:fixed

#472 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:bug, resolution:fixed

#475 Update Wiring Examples.md
  pages/Wiring Examples.md
Labels: type:bug, resolution:fixed

#478 Update README.md
  README.md
Labels: type:feature, resolution:fixed

#480 Document lack of browser support for h264 in webrtc docs
  pages/webrtc.md
Labels: type:feature, resolution:fixed

#482 Update webrtc.md
  pages/webrtc.md
Labels: type:feature, resolution:fixed

#484 Update README.md
  README.md
Labels: type:feature, resolution:fixed

#485 Update README.md
  README.md
Labels: type:feature, resolution:fixed

#487 Update gpio.md
  pages/gpio.md
Labels: type:feature, resolution:fixed

#488 Update Community_FAQ.md
  pages/Community_FAQ.md
Labels: type:feature, resolution:fixed

#494 Update README.md
  README.md
Labels: type:feature, resolution:fixed
