Repository pikvm/pikvm, pull requests merged in 2022-03, with the labels that each got.

#668 Update usb_ethernet.md
  docs/usb_ethernet.md
Labels: type:bug, resolution:fixed

#673 Add information about outgoing serial console
  docs/faq.md
Labels: type:feature

#682 Update first_steps.md
  docs/first_steps.md
Labels: type:feature, resolution:fixed

#690 Update edid.md
  docs/edid.md
Labels: type:feature, resolution:fixed

#694 Update first_steps.md
  docs/first_steps.md
Labels: type:feature

#692 Update first_steps.md
  docs/first_steps.md
Labels: type:feature, resolution:fixed

#695 Update first_steps.md
  docs/first_steps.md
Labels: type:feature, resolution:fixed
