Repository pikvm/pikvm, pull requests merged in 2022-07, with the labels that each got.

#763 Fix kvmd-edidconf --set-audio example
  docs/edid.md
Labels: type:bug, resolution:fixed

#766 Add instructions for using Route53 for DNS
  docs/letsencrypt.md
Labels: type:feature

#773 Update multiport.md
  docs/multiport.md
Labels: type:feature, resolution:fixed

#789 Update flashing_os.md
  docs/flashing_os.md
Labels: type:feature, resolution:fixed

#790 Update vnc.md
  docs/vnc.md
Labels: type:feature, resolution:fixed

#791 Update vnc.md
  docs/vnc.md
Labels: type:bug, resolution:fixed
